#ifndef _TF2_H_
#define _TF2_H_

#define TF2_BACKPACK_MAX_SIZE 100

#define TF2_METAL_MULTIPLIER 3

#define TF2_CRAFT_RANDOM_HAT_ITEM_REQUIREMENT         81
#define TF2_CRAFT_CLASS_SPECIFIC_HAT_ITEM_REQUIREMENT 108

#endif // _TF2_H_
