#ifndef CONSTANTS_H
#define CONSTANTS_H

// version
#define TIBIA_VERSION "8.50"

// equipment slots
typedef enum
{
    TIBIA_EQUIPMENT_SLOT_NULL,
    TIBIA_EQUIPMENT_SLOT_HEAD,
    TIBIA_EQUIPMENT_SLOT_NECK,
    TIBIA_EQUIPMENT_SLOT_BACKPACK, // container
    TIBIA_EQUIPMENT_SLOT_BODY,
    TIBIA_EQUIPMENT_SLOT_RIGHT,
    TIBIA_EQUIPMENT_SLOT_LEFT,
    TIBIA_EQUIPMENT_SLOT_LEGS,
    TIBIA_EQUIPMENT_SLOT_FEET,
    TIBIA_EQUIPMENT_SLOT_RING,
    TIBIA_EQUIPMENT_SLOT_AMMO
} tibiaEquipmentSlot;

#endif // CONSTANTS_H
